config/routes.rb
A4ProjectRevive::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root :to => 'pages#index', :as => 'root', :via => :get

  match '/products' => 'products#index', :as => 'products', :via => :get

  match '/products/kick' => 'products#kicks', :as => 'kicks', :via => :get

  match '/products/punch' => 'products#punches', :as => 'punches', :via => :get

  match '/products/block' => 'products#blocks', :as => 'blocks', :via => :get

  match 'products/:id' => 'products#show', :as => 'product', :via => :get

  match '/results' => 'products#results', :as => 'results', :via => :post

  match '/about' => 'pages#about', :as => 'about', :via => :get

  match '/contact' => 'pages#contact', :as => 'contact', :via => :get

  match '/add_to_cart/:id' => 'products#add_to_cart', :as => 'add', :via => :post

  match '/remove_from_cart/:id' => 'products#remove_from_cart', :as => 'remove', :via => :post

  match '/start_checkout' => 'products#start_checkout', :as => 'start_checkout', :via => :get

  match '/finish_checkout' => 'products#finish_checkout', :as => 'finish_checkout', :via => :post

  match '/view_cart' => 'products#view_cart', :as => 'view_cart', :via => :get

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  attr_accessible :name

  validates :name, :presence => true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :province
  has_many :orders

  attr_accessible :address, :city, :email, :first_name, :last_name, :postal_code, :province_id

  validates :address, :city, :email, :first_name, :last_name, :postal_code, :province_id, :presence => true

  def name
    self.first_name + ' ' + self.last_name
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product

  attr_accessible :order_id, :price, :product_id, :quantity

  validates :order_id, :price, :product_id, :quantity, :presence => true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  has_many :line_items
  has_many :products, :through => :line_items

  attr_accessible :customer_id, :gst_rate, :hst_rate, :pst_rate, :status


  validates :customer_id, :status, :presence => true
  validates :status, :inclusion => { :in => %w(paid pending shipped) }
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content, :title

  validates :content, :title, :presence => true

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders
  has_many :line_items
  belongs_to :category

  attr_accessible :description, :name, :price, :stock_quantity, :image, :category_id

  validates :name, :price, :stock_quantity, :category_id, :presence => true
end

app/models/province.rb
class Province < ActiveRecord::Base
  has_many :customers

  attr_accessible :gst, :hst, :name, :pst

  validates :gst, :hst, :name, :pst, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/page_controller.rb
class PageController < ApplicationController

  def index

  end

  def about

    @page = Page.where("title = 'about'")

  end

  def contact

    @page = Page.where("title = 'contact'")

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

    session[:items] ||= []
    @cart = []
    session[:items].each {|id| @cart << Product.find(id)}

  end

  def about

    @page = Page.where("title = 'about'").first

  end

  def contact

    @page = Page.where("title = 'contact'").first

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :start_cart


  def index

    @products = Product.order('id')

  end

  def show

    @product = Product.find(params[:id])

  end

  def kicks

    @products = Product.joins(:category).where("categories.name = 'Kick'")

  end

  def punches

    @products = Product.joins(:category).where("categories.name = 'Punch'")

  end

  def blocks

    @products = Product.joins(:category).where("categories.name = 'Block'")

  end

  def search

  end

  def results

    if params['category'] == ''

      @products = Product.where("name LIKE ? or description LIKE ?", "%#{params[:keywords]}%", "%#{params[:keywords]}%")

    else

      @products = Product.joins(:category).where("categories.id LIKE ?", "%#{params['category']}%").where("products.name LIKE ? or products.description LIKE ?", "%#{params[:keywords]}%", "%#{params[:keywords]}%")

    end


  end

  def add_to_cart

    id = params[:id].to_i
    session[:items] << id unless session[:items].include?(id)
    redirect_to :action => :index

  end

  def remove_from_cart

    id = params[:id].to_i
    session[:items].delete(id)
    redirect_to :action => :index

  end

  def start_checkout

    @customer = Customer.new
    @provinces = Province.all

  end

  def view_cart

    @products = @cart

  end

  def finish_checkout

    @customer = Customer.new(params[:customer])
    #@customer.first_name = params[:customer][:first_name]
    #@customer.last_name = params[:customer][:last_name]
    #@customer.address = params[:customer][:address]
    #@customer.city = params[:customer][:city]
    #@customer.postal_code = params[:customer][:postal_code]
    #@customer.email = params[:customer][:email]
    #@customer.province_id = params[:customer][:province_id]

    if @customer.save

      @order = @customer.orders.build
      @order.status = 'pending'
      @order.pst_rate = @customer.province.pst
      @order.gst_rate = @customer.province.gst
      @order.hst_rate = @customer.province.hst
      @order.save


      @sub_total = 0

      session[:items].each do |id|
        product = Product.find(id)
        line_item = @order.line_items.build
        line_item.product = product
        line_item.price = product.price
        @sub_total += product.price
        line_item.quantity = 1
        product.stock_quantity -= 1
        product.save
        line_item.save
      end

      session[:items] = []
      individual_total = 0

      pst = @customer.province.pst
      gst = @customer.province.gst
      hst = @customer.province.hst

      pst_string_percentage = pst * 100
      gst_string_percentage = gst * 100
      hst_string_percentage = hst * 100

      pst_float = pst_string_percentage.to_f.round(2)
      gst_float = gst_string_percentage.to_f.round(2)
      hst_float = hst_string_percentage.to_f.round(2)

      total_with_pst = @sub_total * pst
      total_with_gst = @sub_total * gst
      total_with_hst = @sub_total * hst

      @taxes = total_with_pst + total_with_gst + total_with_hst

      @grand_total = @sub_total + @taxes

    else

     flash[:notice] = 'Something went wrong. Please try again.'

    end


  end




protected

  def start_cart

    session[:items] ||= []
    @cart = []
    session[:items].each {|id| @cart << Product.find(id)}

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>A4ProjectRevive</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
    <nav class="navbar navbar-inverse">
      <%= form_tag results_path do %>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Contact Us', contact_path %></li>
        <li>
          <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
              Browse By Category <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu" id="catbutt">
              <li><%= link_to 'All Moves', products_path %></li>
              <li><%= link_to 'Kicks', kicks_path %></li>
              <li><%= link_to 'Punches', punches_path %></li>
              <li><%= link_to 'Blocks', blocks_path %></li>
            </ul>
          </div>
        </li>
        <li><%= text_field_tag :keywords, '', size: 30, class: 'search_field' %></li>
        <li><%= select_tag 'category', options_from_collection_for_select(Category.all, 'id', 'name'), {:prompt => 'All'} %></li>
        <li><%= submit_tag 'Search', class: 'submit_button' %></li>
      </ul>
      <% end %>
    </nav>

  <div class="jumbotron">
    <div class="container">
      <h1>Martial-Arts Moves @ Cost!</h1>
    </div>
    <div class="the_cart">
      <p>
        <%= image_tag('shoppingcart.gif', height: '32', width: '50') %>
        Cart Items: <%= session['items'].count %>
      </p>
      <p>
        <span class="float_left"><%= link_to 'Check Out', start_checkout_path %></span>
      </p>
      <p>
        <%= link_to 'View Cart', view_cart_path %>
      </p>
    </div>
  </div>



  <%= yield %>

</div>

</body>
</html>

app/views/page/_page.html.erb
<h1><%= page.title %></h1>
<%= page.content %>

app/views/page/about.html.erb
<% render @page %>

app/views/page/contact.html.erb
<% render @page %>

app/views/page/index.html.erb
<h1>Page#index</h1>

app/views/pages/_page.html.erb
<h1>Contact Information</h1>
<%= page.content %>

app/views/pages/about.html.erb
<%= render @page %>

app/views/pages/contact.html.erb
<%= render @page %>

app/views/pages/index.html.erb
<h1>We sell moves!</h1>
<section>
And then we mail them to you. Honest.
</section>

app/views/products/_product.html.erb
<div class="col-6 col-sm-6 col-lg-4">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= link_to product.name, product %> - <%= number_to_currency(product.price) %> each
          <% if session[:items].include?(product.id) %>
            <span id="float_right"><%= link_to 'Remove From Cart', remove_path(product), :method => :post %></span>
          <% else %>
            <span id="float_right"><%= link_to 'Add To Cart', add_path(product), :method => :post %></span>
          <% end %>
        </h3>
      </div>
      <div class="panel-body-image">
        <%= image_tag product.image %>
      </div>
    </div>
</div>








app/views/products/_search.html.erb
<%= form_tag results_path do %>
    <%= text_field_tag :keywords %>
    <%= submit_tag 'Search' %>
<% end %>

app/views/products/blocks.html.erb
<h1>Blocks</h1>
<div class="row">
  <%= render @products %>
</div>

app/views/products/finish_checkout.html.erb
<% if flash[:notice] %>
    <%= flash[:notice] %>
<% else %>
    <h1>Checkout Complete</h1>
    Sub total: <%= number_to_currency(@sub_total) %><br />
    Taxes: <%= number_to_currency(@taxes) %><br />
    Grand total: <%= number_to_currency(@grand_total) %><br />
<% end %>

app/views/products/index.html.erb
<h1>All Products</h1>
<div class="row">
    <%= render @products %>
</div>

app/views/products/kicks.html.erb
<h1>Kicks</h1>
<div class="row">
  <%= render @products %>
</div>

app/views/products/punches.html.erb
<h1>Punches</h1>
<div class="row">
  <%= render @products %>
</div>

app/views/products/results.html.erb
<h1>Search Results</h1>
<% if @products.count > 0 %>
    <%= render @products %>
<% else %>
    No results!
<% end %>

app/views/products/search.html.erb
<h1>Search</h1>

<%= form_tag results_path do %>
  <%= text_field_tag :keywords %>
  <%= submit_tag 'Search' %>
<% end %>

app/views/products/show.html.erb
<div class="panel panel-info">
  <div class="panel-body-image">
    <%= image_tag @product.image %>
    <span class = "desc_right">
      <ul>
        <li><h1><%= @product.name %></h1></li>
        <li><%= @product.description %></li>
        <li></li>
        <li><h3><%= number_to_currency(@product.price) %> Each - <%= @product.stock_quantity %> in stock.</h3></li>
      </ul>
    </span>
  </div>
</div>

app/views/products/start_checkout.html.erb
<h1>Checkout</h1>

<section>
  <%= form_for @customer, url: finish_checkout_path(@customer) do |f| %>
      First name: <%= f.text_field :first_name %><br />
      Last name: <%= f.text_field :last_name %><br />
      Address: <%= f.text_field :address %><br />
      City: <%= f.text_field :city %> Province: <%= f.collection_select(:province_id, @provinces, :id, :name) %><br />
      Postal Code: <%= f.text_field :postal_code %><br />
      Email: <%= f.text_field :email %><br />
      <%= f.submit 'Checkout!' %>
  <% end %>
</section>


app/views/products/view_cart.html.erb
<h1>View Cart</h1>
<div class="row">
  <%= render @products %>
</div>